### ISSUE TITLE
ToDO

### ISSUE THREAD

**Issue by woshimaj** [woshimaj/ppt_photo_process#2]
## This Week
- [ ] Activate first test process
(including
- [ ] 1. Images sort by its timestamp
- [ ] 2. An interface for quick view of the images that processed
)
- [ ] Add "# type: hint" to my code

## Much Further
- [ ] Make the codes more OO
- [ ] Saturn
- [x] Uranus
- [ ] Neptune
- [ ] Comet Haley
